# Generated by Django 2.1.2 on 2018-12-04 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='label',
            new_name='tag',
        ),
    ]
