# Generated by Django 2.1 on 2018-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(null=True),
        ),
    ]
