# Generated by Django 2.1.3 on 2018-12-08 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'owner')},
        ),
    ]
