# Generated by Django 2.1.2 on 2019-01-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20181209_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardshare',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='boardshare',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='board',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.DeleteModel(
            name='BoardShare',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
